### ISSUE TITLE
Error with v7…

### ISSUE THREAD

**Issue by albi** [jbdemonte/gmap3#83]
In the console, since v7, I do have the error message: "You have included the Google Maps API multiple times on this page. This may cause unexpected errors."

But if I remove the following line from my code the map won't load.

`<script async defer src="https://maps.googleapis.com/maps/api/js?key=MY_OWN_API_KEY_HERE&language=de&callback=initMap"></script> `

Is v7 already for production? What's the deal with the new API key that is needed? Gmap3 v7 loads the maps libraries on it's own but several times in the head.

**Comment by jbdemonte** [comment]
I guess this is because of your async load, gmap3 detects the sync load and if so, does not load the lib by its own.
I will add a config handler to append API key & options in the async load.
In the interval, you may use a sync load, sorry for the inconvenience.
Regarding the files you mentionned in the head, I guess this is the google lib which handle that, not gmap3 (have a look, they are all differents).

**Comment by albi** [comment]
But what is the correct syntax to add gmap3 v7? If I do not load the map API nothing will show up. There is no way to use the api-key? Is the api-key mandatory?

**Comment by jbdemonte** [comment]
While waiting for the update (coming this week), you can use the synchronous load (http://gmap3.net/quickstart.html)
In your head section:

    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY"></script>

**Comment by albi** [comment]
Thanks for the hint in the right direction. Now it is running without errors.
