### ISSUE TITLE
Clear

### ISSUE THREAD

**Issue by pawelbrachaczek** [jbdemonte/gmap3#89]
Hi again,

Is 'clear' still available in v7? I need to remove marker by id or tag.

**Comment by jbdemonte** [comment]
Hi, this kind of management is no longer available, because it make no sense to provide it, while, you can handle it easily using the list of markers (have a look on the "get").

In the marker options, you can provide whatever you want, so, you can add your tag and so on.
Have a look on this example, I'm adding a _tag into the marker options which allows me to show / hide them: https://github.com/jbdemonte/gmap3/blob/master/dist/examples/cluster-filter.html

Just be careful to not use an official property :)

**Comment by CanMehmetK** [comment]
```
 $('#gm-map').gmap3({}).then(function (infowindow) {
                var map = this.get(0);
                var polyOrMarker = this.get(1);
                // How to remove polyOrMarker ???
            });

$('#gm-map').gmap3({
                zoom: 8,
                scrollwheel: true,
                streetViewControl: false,
                center: [39.22480296, 29.47257692]
            }).polygon( .....
```

I could not find a proper way to remove poly or marker or something else which is not map object....
Please can you give more explain.. Is this way right?
